### ISSUE TITLE
Add ability to specify config file

### ISSUE THREAD

**Issue by joyvuu-dave** [lhagan/coffeelintmate#1]
Hey, thanks for making this plugin. I've been finding it really useful. I was hoping there might be some way to specify one's own config.json file, perhaps by setting the path in a TextMate environment variable and having the program pass that as an argument when running the linter. 

I'd be happy to give it a shot and make a pull request if you were able to point me in the right direction.

**Comment by lhagan** [comment]
Sounds like a good idea. I'd happily accept a pull request, but unfortunately I don't think I can be of much help here. Did you have a look at at how [jslintmate](https://github.com/rondevera/jslintmate) is doing this with `.jslintrc`?
